# Generated by Django 3.0.7 on 2020-09-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_migration_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productpackaging',
            unique_together={('product', 'conditioning', 'type_packaging')},
        ),
    ]
