# Generated by Django 3.0.7 on 2020-09-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_migration_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioning',
            name='products',
            field=models.ManyToManyField(related_name='conditionnings', through='product.ProductPackaging', to='product.Product'),
        ),
    ]
