# Generated by Django 3.0.7 on 2020-09-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_migration_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='conditioning',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
    ]
