# Generated by Django 3.0.7 on 2020-09-16 05:41

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_migration_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[product.models.Category.validate_name], verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='conditioning',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[product.models.Conditioning.validate_name], verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[product.models.Product.validate_name], verbose_name='Nom'),
        ),
    ]
