# Generated by Django 3.0.7 on 2020-09-22 10:52

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_migration_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_line',
            field=models.CharField(max_length=100, null=True, verbose_name="Branche d'activité"),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_sector',
            field=models.CharField(max_length=100, null=True, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='history',
            field=models.TextField(max_length=300, null=True, verbose_name='Histoire'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mail_address_one',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='Messagerie électronique principale'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mail_address_two',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='Messagerie électronique secondaire'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mission',
            field=models.TextField(max_length=300, null=True, verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sales_turnover',
            field=models.DecimalField(decimal_places=2, max_digits=22, null=True, verbose_name="Chiffre d'affaire"),
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone_two',
            field=phone_field.models.PhoneField(max_length=20, null=True, unique=True, verbose_name='N° téléphone secondaire'),
        ),
        migrations.AlterField(
            model_name='company',
            name='web_site',
            field=models.URLField(null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='legal_position',
            field=models.CharField(max_length=100, null=True, verbose_name='Situation juridique'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='web_site',
            field=models.URLField(null=True, verbose_name='Site web'),
        ),
    ]
